// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://breoohrknvxkefzykawq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZW9vaHJrbnZ4a2VmenlrYXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTE0MzksImV4cCI6MjA3Mzc2NzQzOX0.zcfA6KG5mTY595Z_D5Ca6Ums3mLyu6EGmf3Ln6cFJIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});